// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdutJHkjL_z8lhylpCmPm8Af6qX622rpY',
    appId: '1:537487807705:web:c9aeeb814f362c53821ac8',
    messagingSenderId: '537487807705',
    projectId: 'expense-6b6cc',
    authDomain: 'expense-6b6cc.firebaseapp.com',
    storageBucket: 'expense-6b6cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdLbGz8AHoryap6HMYLLwvZi7jC0s4Ro4',
    appId: '1:537487807705:android:4f95212aad9d6361821ac8',
    messagingSenderId: '537487807705',
    projectId: 'expense-6b6cc',
    storageBucket: 'expense-6b6cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOFERclvBcxBaNWt0DIa0TGNILfW-ly9s',
    appId: '1:537487807705:ios:de7902839bd0d725821ac8',
    messagingSenderId: '537487807705',
    projectId: 'expense-6b6cc',
    storageBucket: 'expense-6b6cc.appspot.com',
    iosBundleId: 'com.example.assessmentApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOFERclvBcxBaNWt0DIa0TGNILfW-ly9s',
    appId: '1:537487807705:ios:de7902839bd0d725821ac8',
    messagingSenderId: '537487807705',
    projectId: 'expense-6b6cc',
    storageBucket: 'expense-6b6cc.appspot.com',
    iosBundleId: 'com.example.assessmentApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdutJHkjL_z8lhylpCmPm8Af6qX622rpY',
    appId: '1:537487807705:web:1269e5e09f19ce22821ac8',
    messagingSenderId: '537487807705',
    projectId: 'expense-6b6cc',
    authDomain: 'expense-6b6cc.firebaseapp.com',
    storageBucket: 'expense-6b6cc.appspot.com',
  );

}